name: test build and deploy

on:
  push:
    branches: [ mutant ]
  pull_request:
    branches: [ mutant ]

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: 'node_modules'
          key: hash-${{ hashFiles('yarn.lock') }}
      - name: install deps
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: 'node_modules'
          key: hash-${{ hashFiles('yarn.lock') }}
      - name: install deps
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: 'node_modules'
          key: hash-${{ hashFiles('yarn.lock') }}
      - name: install deps
        run: yarn install --frozen-lockfile
      - name: deploy
        run: yarn deploy
